In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\leela\Desktop\Excel\healthcare_dataset\healthcare_dataset.csv")

In [4]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [5]:
new_cols={'Blood Type':'Blood_Type','Medical Condition':'Medical_Condition','Date of Admission':'Admission_Date',
        'Insurance Provider':'Insurance_Provider','Billing Amount':'Billing_Amount','Admission Type':'Admission_Type',
        'Discharge Date':'Discharge_Date','Test Results':'Test_Results'}
df.rename(columns=new_cols,inplace=True)

In [6]:
df=df.drop_duplicates().reset_index(drop=True)

In [7]:
df['Name']=df['Name'].str.strip().str.title()

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 54966 entries, 0 to 54965
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                54966 non-null  str
 1   Age                 54966 non-null  int64
 2   Gender              54966 non-null  str
 3   Blood_Type          54966 non-null  str
 4   Medical_Condition   54966 non-null  str
 5   Admission_Date      54966 non-null  str
 6   Doctor              54966 non-null  str
 7   Hospital            54966 non-null  str
 8   Insurance_Provider  54966 non-null  str
 9   Billing_Amount      54966 non-null  float64
 10  Room Number         54966 non-null  int64
 11  Admission_Type      54966 non-null  str
 12  Discharge_Date      54966 non-null  str
 13  Medication          54966 non-null  str
 14  Test_Results        54966 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 6.3 MB

In [17]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood_Type            0
Medical_Condition     0
Admission_Date        0
Doctor                0
Hospital              0
Insurance_Provider    0
Billing_Amount        0
Room Number           0
Admission_Type        0
Discharge_Date        0
Medication            0
Test_Results          0
dtype: int64

In [18]:
df.describe()

                Age  Billing_Amount   Room Number
count  54966.000000    54966.000000  54966.000000
mean      51.535185    25544.306284    301.124404
std       19.605661    14208.409711    115.223143
min       13.000000    -2008.492140    101.000000
25%       35.000000    13243.718641    202.000000
50%       52.000000    25542.749145    302.000000
75%       68.000000    37819.858159    401.000000
max       89.000000    52764.276736    500.000000

In [8]:
df['Admission_Date']=pd.to_datetime(df['Admission_Date'])
df['Discharge_Date']=pd.to_datetime(df['Discharge_Date'])

In [29]:
df.head(5)

,Name,Age,Gender,Blood_Type,Medical_Condition,Admission_Date,Doctor,Hospital,Insurance_Provider,Billing_Amount,Room Number,Admission_Type,Discharge_Date,Medication,Test_Results
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.28,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.33,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.10,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.32,458,Urgent,2022-10-09,Penicillin,Abnormal

In [24]:
df['Billing_Amount']=df['Billing_Amount'].abs().round(2)

In [26]:
df['Doctor']=(df['Doctor']
    .str.replace(r'^(Mr\.|Mrs\.|Ms\.|Miss|Dr\.)\s+','',regex=True)
    .str.replace(r'\s+(MD|DDS|DVM|PHD|Jr\.|Sr\.|II|III|IV)$','',regex=True)
    .str.strip())

In [28]:
df['Hospital']=(df['Hospital']
    .str.replace(',','',regex=True)
    .str.strip()
    .str.replace(r'^and\s+','',regex=True)
    .str.replace(r'\s+and$','',regex=True)
    .str.strip())

In [31]:
print((df['Discharge_Date']<df['Admission_Date']).sum())

0

In [32]:
print(df['Age'].min(),df['Age'].max())

13 89

In [35]:
for col in ['Gender','Blood_Type','Medical_Condition','Insurance_Provider','Admission_Type','Medication',
    'Test_Results']:
    print(df[col].value_counts(),'\n')

Gender
Male      27496
Female    27470
Name: count, dtype: int64

Blood_Type
A-     6898
A+     6896
B+     6885
AB+    6882
AB-    6874
B-     6872
O+     6855
O-     6804
Name: count, dtype: int64

Medical_Condition
Arthritis       9218
Diabetes        9216
Hypertension    9151
Obesity         9146
Cancer          9140
Asthma          9095
Name: count, dtype: int64

Insurance_Provider
Cigna               11139
Medicare            11039
UnitedHealthcare    11014
Blue Cross          10952
Aetna               10822
Name: count, dtype: int64

Admission_Type
Elective     18473
Urgent       18391
Emergency    18102
Name: count, dtype: int64

Medication
Lipitor        11038
Ibuprofen      11023
Aspirin        10984
Paracetamol    10965
Penicillin     10956
Name: count, dtype: int64

Test_Results
Abnormal        18437
Normal          18331
Inconclusive    18198
Name: count, dtype: int64

In [34]:
df['Length_Of_Stay']=(df['Discharge_Date']-df['Admission_Date']).dt.days
df['Admission_Year']=df['Admission_Date'].dt.year

In [37]:
df['Age_Group']=pd.cut(df['Age'],
    bins=[0,15,30,60,120],
    labels=['Child','Adult','Middle Aged','Old Age'],
    right=False)

In [38]:
df['Age_Group'].value_counts()

Age_Group
Middle Aged    24413
Old Age        20948
Adult           9573
Child             32
Name: count, dtype: int64

In [36]:
df.head(10)

,Name,Age,Gender,Blood_Type,Medical_Condition,Admission_Date,Doctor,Hospital,Insurance_Provider,Billing_Amount,Room Number,Admission_Type,Discharge_Date,Medication,Test_Results,Length_Of_Stay,Admission_Year
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.28,328,Urgent,2024-02-02,Paracetamol,Normal,2,2024
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.33,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,2019
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.10,205,Emergency,2022-10-07,Aspirin,Normal,15,2022
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78,450,Elective,2020-12-18,Ibuprofen,Abnormal,30,2020
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.32,458,Urgent,2022-10-09,Penicillin,Abnormal,20,2022
5,Emily Johnson,36,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,UnitedHealthcare,48145.11,389,Urgent,2023-12-24,Ibuprofen,Normal,4,2023
6,Edward Edwards,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.87,389,Emergency,2020-11-15,Paracetamol,Inconclusive,12,2020
7,Christina Martinez,20,Female,A+,Cancer,2021-12-28,Suzanne Thomas,Powell Robinson and Valdez,Cigna,45820.46,277,Emergency,2022-01-07,Paracetamol,Inconclusive,10,2021
8,Jasmine Aguilar,82,Male,AB+,Asthma,2020-07-01,Daniel Ferguson,Sons Rich,Cigna,50119.22,316,Elective,2020-07-14,Aspirin,Abnormal,13,2020
9,Christopher Berg,58,Female,AB-,Cancer,2021-05-23,Heather Day,Padilla-Walker,UnitedHealthcare,19784.63,249,Elective,2021-06-22,Paracetamol,Inconclusive,30,2021

In [42]:
df=df.drop(columns=['Room Number','Age'])

In [43]:
df.head(10)

,Name,Gender,Blood_Type,Medical_Condition,Admission_Date,Doctor,Hospital,Insurance_Provider,Billing_Amount,Admission_Type,Discharge_Date,Medication,Test_Results,Length_Of_Stay,Admission_Year,Age_Group
0,Bobby Jackson,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.28,Urgent,2024-02-02,Paracetamol,Normal,2,2024,Middle Aged
1,Leslie Terry,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.33,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,2019,Old Age
2,Danny Smith,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.10,Emergency,2022-10-07,Aspirin,Normal,15,2022,Old Age
3,Andrew Watts,Female,O+,Diabetes,2020-11-18,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78,Elective,2020-12-18,Ibuprofen,Abnormal,30,2020,Adult
4,Adrienne Bell,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.32,Urgent,2022-10-09,Penicillin,Abnormal,20,2022,Middle Aged
5,Emily Johnson,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,UnitedHealthcare,48145.11,Urgent,2023-12-24,Ibuprofen,Normal,4,2023,Middle Aged
6,Edward Edwards,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.87,Emergency,2020-11-15,Paracetamol,Inconclusive,12,2020,Adult
7,Christina Martinez,Female,A+,Cancer,2021-12-28,Suzanne Thomas,Powell Robinson and Valdez,Cigna,45820.46,Emergency,2022-01-07,Paracetamol,Inconclusive,10,2021,Adult
8,Jasmine Aguilar,Male,AB+,Asthma,2020-07-01,Daniel Ferguson,Sons Rich,Cigna,50119.22,Elective,2020-07-14,Aspirin,Abnormal,13,2020,Old Age
9,Christopher Berg,Female,AB-,Cancer,2021-05-23,Heather Day,Padilla-Walker,UnitedHealthcare,19784.63,Elective,2021-06-22,Paracetamol,Inconclusive,30,2021,Middle Aged

In [45]:
df.to_csv(r"C:\Users\leela\Desktop\Excel\healthcare_dataset\cleaned_healthcare_dataset.csv",index=False)